# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sema < Formula
  desc ""
  homepage "https://github.com/sharpvik/sema"
  version "3.0.2"

  on_macos do
    url "https://github.com/sharpvik/sema/releases/download/v3.0.2/sema_3.0.2_darwin_all.tar.gz"
    sha256 "cf5cd11c00dc7f4a933c9df8dcd286105fc5525a6a4a8eec9ce5b62e97d080e0"

    def install
      bin.install "sema"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sharpvik/sema/releases/download/v3.0.2/sema_3.0.2_linux_arm64.tar.gz"
      sha256 "32ba15c2b2c4df361142e8c93540b342779e126d76f9ef2ab23e3b8d78efc7b9"

      def install
        bin.install "sema"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sharpvik/sema/releases/download/v3.0.2/sema_3.0.2_linux_amd64.tar.gz"
      sha256 "9de49627d41061724f72c82845ec4ad74c60e4172b61a1cf7a182ff93d5f16a2"

      def install
        bin.install "sema"
      end
    end
  end
end
