# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sema < Formula
  desc ""
  homepage "https://github.com/sharpvik/sema"
  version "3.0.3"

  on_macos do
    url "https://github.com/sharpvik/sema/releases/download/v3.0.3/sema_Darwin_all.tar.gz"
    sha256 "aecd8ce56d29c92a2c4a28d8d40791d0ecedee930a76ab497002f71446ac849b"

    def install
      bin.install "sema"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sharpvik/sema/releases/download/v3.0.3/sema_Linux_arm64.tar.gz"
      sha256 "e61bcf4506535b3793927a41032a03676636862b1d6c0f288fb305ab176743cb"

      def install
        bin.install "sema"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sharpvik/sema/releases/download/v3.0.3/sema_Linux_x86_64.tar.gz"
      sha256 "0d81ea77ff5a3d52be65be1885ce7ffee8fbe44a533dc546aa1ebdf56f353028"

      def install
        bin.install "sema"
      end
    end
  end
end
